---
title: "엔트로피 - 제 1부 세계관의 변화"
author: "Jae Kwan Koo"
output:
  html_document:
    fig_height: 6
    fig_width: 10
    highlight: textmate
    toc: yes
    toc_depth: 4
    toc_float: yes
  word_document: default
  github_document:
    toc: yes
    toc_depth: 4
---  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```  

# 제 1부 세계관의 변화  

## 세계관  

모든 사회에서 발견되는 문화형성의 필수요소인 일상생활에서 `‘어떻게’`와 `‘왜’`를 설명할 질서를 확립하는 등 오랫동안 인간은 자신의 생활을 구성하는 기준의 틀을 만들 필요성을 느꼈다.  

하지만, 이런한 세계관이 자신의 행동방식이나 현실인식방법에 어떻게 영향을 미치는지는 대부분이 인식하지 못한다.(아무도 의문을 제기하지 않을 만큼 어릴 적부터 마음 속에 내재됨)  

세게관은 우리의 현실인식과정에 너무나도 강력한 힘을 발휘하고 있기 때문에, 우리는 세상을 바라보는 다른 시각도 있음을 전혀 상상하지 못한다.  


우리는 아직 **뉴턴**이 만든 17세기의 **기게론적 우주관**의 영향아래 살고 있다. 이제 **엔트로피 법칙**이라는 새로운 세게관이 떠오르고 있다.  

<br>
<br>

<**엔트로피 법칙**> - 열역학 제 2법칙  

* 아인슈타인 : “모든 과학에 있어 제 1법칙”  
* 아서에딩턴 : “전우주를 통틀어 최성의 형이상학적 법칙”  

`제1법칙` : 우주 안의 모든 물질과 에너지는 불변하며, 창조될 수도 없다. 단지 형태만 바뀔 뿐이다  

`제2법칙` : 물질과 에너지는 한 방향으로만 변한다. 유용한 상태에서 무용한 상태로, 획득가능한 상태에서 획득불가능한 상태로, 질서있는 상태에서 무질서한 상태로만 변한다  

<br>
<br>


우주 안의 모든 것은 일정한 구조와 가치로 시작해서 무질서한 혼돈과 낭비의 상태로 나아가며, 이 방향을 거꾸로 되돌리는 것은 불가능하다.  
**우주내 어떤 시스템에 존재하는 유용한 에너지가 무용한 형태로 바귀는 정도를 재는 척도**  


엔트로피 법칙은 기존의 패러다임이 왜 무용지물인가를 이해하게 해준다.  
새로운 패러다임 속에서 불편할 때도 있겠지만, 우리의 후대는 엔트로피적 세게관을 제 2의 천성처럼 받아들일 것이다.  


<br>
<br>

한편에서는 엔트로피 법칙이 어떠한 에외도 없이 세상의 모든 물리현상을 지배한다는 사실을 완강하게 부인하는 사람들도 있을 것이다.  
열역한 법칙은 세상에서 벌어지는 모든 물리적 현상을 지배하는 과학적인 틀을 제공한다.  
**엔트로피 법칙이 물리적 세게(모든 것이 유한하고 모든 생물체가 삶의 과정을 마치면 그 존재가 종식되는 세계)만을 다룬다**  

<br>

엔트로피 법칙 –시간과 공간의 `수평적 세계`를 지배하는 법칙, 정신적 초월이라는 `수직적 세계`에는 적용 불가  


`정신` - 비물질적 차원으로 경계나 제한이 없다.  

물질세계와 정신세계의 관계 = 부분과 전체의 관계  

부분은 전체 속에서 기능한다.  

엔트로피 법칙 : 시간, 공간, 물질세계를 지배하는 반면, 그 자신은 엔트로피 법칙을 생각해낸 정신적 힘에 종속되는 것  

<br>
<br>



## 그리스인들과 역사의 다섯 단계 : 순환과 몰락  

* 플라톤, 아리스토텔레스 등 그리스인 – 역사를 지속적인 쇠락의 과정으로 보았다. 가장 좋은 사회질서는 변화가 가장 적은 것  

* 호라티우스(로마인) – “시간은 세계의 가치를 떨어뜨린다.”, 열역학 법칙을 몰랐지만 엔트로피 법칙의 본질을 훌륭하게 요약  

<br>
<br>

그리스 신화에서 역사는 다섯 단계로 구분, 각 단계는 앞선 단계보다 쇠퇴해 있고 살기도 힘들다.  

* `헤시오도스(그리스 역사가)` : 다섯 단계를 황금시대, 은의시대, 청동시대, 영웅의 시대, 철의 시대(풍요와 만족의 시대인 황금시대가 가장 좋은 시기)로 구분  

* 토머스 홉스 : 인간의 자연상태를 "외롭고, 가난하고, 괴롭고,야만적이고, 짧은 삶”으로 인식  

<br>
<br>

오늘날 인류학자들의 생각은 `헤시오도스의 해석`으로 기울어지고 있다.  

우리 같은 사람들은 인간의 역사가 초기 원시인들의 힘겨운 노동에서 오늘날 쾌적하고 여유있는 생활로 점차 발전해왔다고 믿지만, 우리 현대인들은 일주일에 40시간 일하고 1년에 2~3주 정도 가지는 휴가를 자랑스럽게 생각하지만, 대부분의 수렵채취인을 살펴보면 그들은 일주일에 12~20시간밖에 일하지 않고 몇 주, 몇 달에 걸쳐 전혀 일을 하지 않고 놀이, 스포츠, 예술, 음악, 춤, 제례의식, 상호방문 등 여가시간을 즐긴다.  

<br>
<br>

* 그리스 사람들 :세상이 신에 의해 창조되었기 때문에 완벽하기는 하지만 영원하지는 못하다.  
더욱 큰 변화와 발전을 더욱 심한 쇠락과 혼돈으로 해석.  
목표는 변화로부터 최대한 보호된 세계를 다음 세대에게 물려주는 것  

<br>


**역사는 항금시대에만 완벽한 질서를 유지한 후, 은의 시대에서부터 역사의 전과정에 걸쳐 쇠락의 과정을 밟았다.**  
결국 궁극적인 우주는 혼돈을 향해 가고, 이때 신들이 다시 나타나 태초의 완벽한 상태로 회복시킨다.  
따라서 역사는 완벽을 향한 발전이 아니라 질서에서 혼돈으로 움직여가는 **사이클의 영원한 반복**인 것이다.  

<br>
<br>

## 기독교적 세계관  

현대인이 중세로 가더라도 즉각 알아볼 수 있는 것이 많을 만큼 13세기는 그리 먼 과거가 아니다.  

`현대인`과 `농노`는 날씨 이야기가 끝나고 나면 할 이야기가 별로 없을 것이다.  
현대인은 농노에게 삶의 목표에 대해 관심을 갖는다.(당신은 세상을 위해 무엇을 하려고 하는가?, 어떻게 해서 삶을 개선해나가려 하는가?, 자식들에게 무엇을 남기고 싶은가?)  

현대인이 너무 어려운 이야기를 했거나, 농노가 정신적으로 미성숙해서 의견교환을 할 능력이 없기 때문이 아니라, 농노는 삶, 역사, 현실 등에 대해 현대인과는 판이한 생각을 가지고 있기 때문이다.  

<br>


**중세 전반에 걸쳐 서유럽을 지배했던 기독교적 역사관은 이 세상에서의 삶을 다음 생을 향해 가는 중간과정으로 생각했다.**  

그리스적인 순환의 개념은 버렸지만, 역사를 쇠락의 과정으로 인식했다. 기독교 신학에서 역사는 분명한 시작과 과정, 종말을 가지고 있다.(창조, 구원, 최후의 심판 등)  

기독교적 역사관에서 인간의 역사는 순환하지 않고 일직선으로 나아가지만 그렇다고 완벽한 상태를 향해 발전해나가는 것은 아니다.  
오히려 역사는 계속해서 악의 힘이 혼돈과 해체의 씨앗을 지상에 뿌리는 것으로 인식된다.  


<br>

`‘원죄’`개념은 중요하다  
원죄로 인해 인간은 자신의 운명을 개선할 여지조차 박탈당한다. 인간은 역사에 뭔가 변화를 가하는 것 자체가 상상할 수 없는 일이다.  

중세사람들은 신이 모든 사건 하나하나를 통제하는, 완벽하게 질서정연한 구조물로 세상을 파악했다. 어떤 일이 일어나는 여부는 신의 뜻이었다. **역사를 만드는 것은 신이었지 인간이 아니었던 것이다.**  

그리스인들처럼 중세인들도 역사를 성장,물질획득의 과정으로 파악하지 않고 즉, ‘뭔가를 성취하는 것’이 아닌 구원을 얻는 것이다.  

사회는 이 목적을 달성하기 위한 유기체이고 사회는 신이 이끄는 일종의 도덕적 생물체이고 그 안에서 각 개인은 자신의 역할을 수해해야 했다.  

<br>
<br>



## 현대적 세계관

1750년 소르본 대학의 `자크 튀르고` 교수의 수업이 끝나고 `프랑크 마누엘`은 “그의 강의는 아득한 고대에서 현대에 이르기까지의 세계사에 새로운 개념을 부여했고, 최초로 ‘**진보**’라는 중요한 사상을 창시했다.”  

<br>

* 튀르고 : 역사의 순환과 지속적인 쇠락을 거부, “역사는 일직선으로 진행하는 것이며, 각 단계는 앞선 단게보다 진보한 모습을 보여준다.  
역사는 축적의 산물임과 동시에 진보하는 것이다.”  

정체상태를 찬양한 그리스철학자, 중세 교회의 신학자들과 달리 끊임없는 변화와 움직임의 미덕을 역사에 도입. 물론 진보는 불규칙하고 가끔 벽에 부딪히기도 하며 심지어 퇴보하기까지 한다는 사실에 동의했다.  


13세기 프랑스의 샤르트르에 대성당이 건립되던 시기, 1750년의 기억할 만한 강의 사이에 유럽 사람들의 마음에는 근본적인 변화가 일어난 것이 현대적 세게관의 모태이다. 이것이 성장하고 성숙하여 오늘 날 우리가 물려받은 세계관이 되었다.  

<br>
<br>


## 기계의 시대  

**정밀, 신속, 정확**이 가장 중요한 가치이다.  
"설계, 구상, 제작 모두 완벽해서 이 물건은 저절로 돌아가겠군요”가 최고의 칭찬이다.  

<br>

현대인에 있어 역사는 기술발달의 과정이다.  
* 진보 : 완벽한 기계를 만드는 일에 '맞물려’있다.  

우리는 기계가 설정한 틀에 따라 산다.  
그러나 우리는 기계가 우리 삶의 외부적 측면에 대해 갖는 중요성은 기꺼이 인정하지만 그것이 우리 존재의 내부까지 뚫고 들어온 모습을 직시하는 데는 훨씬 소극적이다.  

기계가 우리 내부로 너무 깊숙이 들어와버렸기 때문에 기계가 어디서 끝나고 우리는 어디서 시작되는지를 알기는 매우 어렵다.  

<br>
<br>

## 기계론적 세계관의 창시자들  

18세기 중엽 : 기계 패러다임의 모든 요소들이 하나의 설계로 통합되었다.  

기계론적 세계관은 `프랜시스 베이컨(Francis Bacon)`, `르네 데카르트(Rene Descartes)`, `아이작 뉴턴(Issac Newton)`의 공동작품  

300년 지난 오늘날까지 우리는 이들이 만든 사상의 영향 아래 살고 있다.  

<br>

* 프랜시스 베이컨 - 현대실용주의자의 원조  
    * 고대 긔스 세계관을 비난  
    * 1620년에 출판된 **신기관론**에서 플라톤, 아리스토텔레스, 호머의 저술들을 "탁상공론자들의 학문"으로 깎아내림  
    * "그리스인들은 어린아이 같은 특성을 갖고 있었음에 틀림없다. 말만 넘치지 해놓은 일은 없다."  
    * "주장하는 바는 거창하지만 인간의 조건을 개선하거나 향상시키기 위한 실험은 단 한번도 해본 적이 없다."  

<br>
    
* 과학  
    * 그리스인 : 사물의 형이상학적인 "왜"를 탐구  
    * 베이컨 : 학문이란 사물의 "어떻게"를 연구하는데 바쳐져야 함  
    
<br>
    
베이컨은 세상을 대하는 새로운 방법의 필요성을 말한다.  
그것은 '인간의 영역을 확장하고 모든 것들을 가능하게 하는'방법이다.  

이는 과학적인 방법으로 관찰자를 관찰의 객체와 분리하여 '객관적 지식'의 개발을 지향하는 중립적 위치를 확보하는 것이 목적  

"객관적 지식으로 무장하면 모든 자연물을 지배할 수 있다. 인간의 신체, 의학, 기계적 힘 그리고 무수한 다른 것들을 지배할 수 있는 것"  


"객관적으로 생각해봐", "증명해봐", "사실만 얘기해"  

<br>

* 데카르트 - 기계론적 세계관의 진정한 신봉자  
    * 세계를 이해하고, 암호를 풀고, 인간의 목적에 맞게 통제하는 열쇠는 수학이다.  
    * 수학은 모든 것의 원천  
    * 중요한 것은 오직 공간과 위치이다.  
    
수학은 총체적 질서의 표현이며, 데카르트의 세계에서 모든 것들은 저마다 자리가 있고 상호간 조화를 유지하고 있다. 세계는 정밀한 것이지 혼란스러운 것이 아니었다.  
역사를 혼돈과 쇠락 과정의 전개로 파악하는 그리스적 세계관은 수학적이 아니므로 옳지 않다.  
기계론이 세계관으로서 그 기능을 다하려면 무엇보다도 예측이 가능해야 했다. 데카르트는 신을 교묘한 방법으로 은퇴시켰다.  


<br>

데카르트는 인간이 세계의 진리를 알아내고 그 주인이 될 수 있을 것이란느 '신념'을 주었다. 뉴턴이 나타나 그 신념을 실현할 도구를 제공했다.  

* 뉴턴  
    * 기계적 운동을 설명할 수학적 방법론을 찾음  
    
    
기계론적 세계관은 운동하는 물체만을 다루었다. 왜냐하면 운동하는 물체만이 수학적으로 측정될 수 있기 때문이다.  
따라서 이 세계관은 기계를 위한 것이지 인간을 위한 것이 아니다.  


<br>

* 알프레드 노스 화이트헤드 - 뉴턴이 제창한 기계론적 세계의 한계에 대해 논평
    * 시간-공간 안의 일정한 장소가 확정되기만 하면 특정 물체와 시간-공간 사이의 관계를 충분히 설명할 수 있다. "그것은 거기, 그 장소에 있다"  
    
    
    
기계론적 패러다임은 천하무적임이 증명됨 - 우주는 어떻게 돌아가는가에 답이 나옴  

하지만 여전히 사회 안에서 사람들의 정상적인 활동이 뒤엉키고 혼돈스러운 것처럼 보이는가? - **사회가 잘못되어 있다면 이유는 하나 뿐이다. 우주를 지배하는 자연의 법칙을 사회가 따르지 않았기 떄문이다.**  


<br>
<br>

우주의 법칙과 사회의 기능원리 사이의 관계를 연구하기 시작한 사람들이 있다.  

* **존 로크** - `정부`와 `사회`의 역할을 기계 패러다임 안으로 끌어들임  
    * 왜 인간의 활동은 이처럼 혼돈스러운가? : 세계를 오랫동안 지배해온 신 중심주의에서 비롯된 비이성적 전통과 관습에 따라 사회적 질서가 만들어졌기 때문  
    * "각 개인이 종교에 관심을 갖는 것은 합당한 일일 수도 있다. 그러나 종교가 공공활동의 기반이 되어서는 안된다."  
    * 베이컨이 신을 자연에서 밀어낸 것처럼 로크는 신을 인간사에서 제거  
    * 인간들로 구성된 사회는 단 한가지 목표만 가지게 되는데, 구성원의 재산축적을 보호하고 허용하는 것이다.(순수한 자기이익의 추구가 사회 구성의 유일한 기반->유물론적, 개인주의적)  
    * "자연을 거부하는 것이야말로 행복을 향한 길. 인간은 자연의 멍에에서 해방되어야 한다."  
    * "자연은 인간의 노통과 합쳐져 생산성을 가져야만 비로소 가치있는 것이 된다"  
    

물론 자연상태에서 원시인들은 풍요한 자연에서 지극히 한정된 부밖에는 얻지 못했음을 로크도 시인한다. 그런데, 자연을 정복하여 부를 창출할 수 있는 지식을 갖지 못한 원시인이 더 많은 부를 얻으려면 공동체의 다른 구성원들이 부를 출적할 수 있는 기회를 박탈하는 방법밖에 없었을 것  
그러나, 이성에 입각한 공동체 안에서는 돈이 교환수단이 될 것이고 무한한 부의 축적이 가능해질 것이다.  


    

<br>
<br>




* **애덤 스미스** - `경제`를 기계론 안으로 끌어들임  
    * [국부론] : 움직이는 천체가 자연의 일정한 법칙을 따르는 것처럼 우리 경제도 마찬가지다.  
    * 경제학의 법칙을 보면 가장 효율적인 경제운영방법은 `자유방임`이다.  
    * 존 로크와 마찬가지로 인간활동의 기본은 물질적 자기 이익의 추구  
    * 존 로크가 사회적 관계에서 도덕성을 제거한 것철머 경제에서 도덕성을 제거  
    
       
    
법칙을 따르면 경제는 성장하지만, 정부의 규제와 통제 때문에 경제는 부자연스러운 방향으로 끌려가고 따라서 자연의 법칙이 깨지는 것이다.  

두 사람의 주장대로라면, 각 개인이 이기적으로 행동하는 것에 따라 부의 희소성은 부의 잉여로 바뀔 수 있다.  

어떤 식으로든 경제에 도덕성을 강제하려고 하면 "보인지 않는 손"의 법칙이 깨질 뿐이다.  
시장을 통제하는 데 있어서 '자연적' 힘보다 더 효율적인 것은 없기 때문에 합리적이고 획득을 추구하는 개인간 자유롭고 방해받지 않는 거래와 경쟁을 통해서만 부는 가장 잘 추구될 수 있다고 주장하는 것  

<br>
<br>

### <요약>  

**베이컨, 데카르트, 뉴턴, 로크, 스미스 : 기계론적 세계관을 널리 퍼뜨린 사람**  

이들이 주장한 기본가설은 오늘날까지도 우리를 지배하고 있음.  

<br>

1. 우주에는 정밀한 수학적 질서가 있고 이 질서는 천체의 움직임을 관찰하여 도출할 수 있다.  
불행히도 지구상 대부분의 것은 원시상태에 있어 혼돈과 혼란 속에 있으므로 재배열하여 우주에서 우리가 볼 수 있는 것과 같은 질서를 지구상에 도입  
-> 어떻게 하면 자연의 것들을 잘 배열?  

- 역학의 과학적 법칙을 이용하여 인간의 물질적 자기 이익이 증대되는데 가장 적합하도록 자연을 재배열  
- 물질적 부가 축적될수록 세계는 더 질서있게 됨(과학, 기술은 이를 실천하는 도구)  

<br>
<br>

* 찰스다윈 - 기계론적 세계관이 최대의 승리를 누림  
    * 종의 기원  
    
    
* 허버트 스펜서같은 사회 철학자  
    * 다윈의 진화론을 "세계는 진보한다"는 주장의 증거로 삼음.  
    * 자연도태의 개념을 적자생존의 개념으로 변형  
    
적자생존의 해석 : "자연상태에서 각 개체는 다른 모든 생물체와 무자비한 전쟁상태에 있다. 끝까지 살아남아서 자신의 유전자를 다음 세대에 전하는 개체들은 스스로의 물질적 이익을 가장 잘 지킨 개체들이다."  
-> 각 세대는 앞선 세대보다 자기 이익을 극대화할 능력과 물질적 풍요를 충족시킬 능력이 뛰어나다는 이야기(기계론적 세계관의 주요 가설을 완벽하게 반복)  

<br>


**진보**  
- 기계론의 가장 큰 특징  
- 목적 : 자연과정의 일부를 더 큰 가치, 더 큰 구조, 더 큰 질서의 형태로 바꾸어 당초의 상태보다 더 나은 상태를 만드는 것.  

