---
title: "엔트로피 - 제 2부 엔트로피 법칙"
author: "Jae Kwan Koo"
output:
  html_document:
    fig_height: 6
    fig_width: 10
    highlight: textmate
    toc: yes
    toc_depth: 4
    toc_float: yes
  word_document: default
  github_document:
    toc: yes
    toc_depth: 4
---  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```  

# 제 1부 엔트로피 법칙  

## 엔트로피 법칙  

* 막스 글루크만  
    * "과학이란 우리 세대의 가장 어리석은 사람조차 지난 세대의 천재보다 앞서갈 수 있는 학문"  


현재 열역학 제1법칙과 제2법칙은 물리학 입문시간에 강의될 정도로 그 내용이 기초적이면서 단순하고 상식적이지만, 지금의 모습을 갖추기까지 매우 힘든 과정이 있었고 그 사이 수많은 학자들이 수많은 이론과 추측을 내놓았다.  

"세상에 공짜는 없다", "엎질러진 물이다", "자연의 법칙을 이길 수는 없다" 등의 이야기가 일상생활에서 증명되는 것을 본 사람들은 이미 제 1법칙과 제 2법칙을 알고 있는 사람이다.  

<br>


"열역학"이 매우 복잡한 개념처럼 들리지만 제 1법칙과 제 2법칙을 하나의 문장으로 설명하면 다음과 같다.  

* "우주의 에너지 총량은 일정하며(제1법칙), 엔트로피 총량은 지속적으로 증가한다.(제2법칙)  
    * 제1법칙 : 에너지 보존의 법칙으로서, 에너지는 결코 창조되거나 파괴될 수 없으며, 한 가지 형태에서 다른 형태로 변화할 뿐이다.  
    * 제2법칙 : 에너지는 한 상태에서 다른 상태로 옮겨갈 때마다 '일할 수 있는 유용한 에너지가 손실' 이것은 `엔트로피(Entropy)`이다.  
    

<br>
<br>

* `엔트로피`  
    * **더 이상 일로 전환될 수 없는 에너지의 양을 측정하는 수단**
    * 어떤 시스템 내에 존재하는 무용한 에너지의 총량  
    

  엔트로피가 증가한다는 것은 유용한 에너지가 줄어든다는 것을 의미  
  자연계에서 무슨 일이 일어난다는 것은 일정량의 에너지가 무용한 에너지로 전환된다는 뜻  

* 오염  
    * 무용한 에너지로 전환된 유용한 에너지의 총량
    * 엔트로피의 또다른 이름에 불과
    

<br>
<br>

* 평형상태 : 엔트로피가 극대점에 달한 상태, 일을 할 수 있는 자유롭고 유용한 에너지가 더 이상 존재하지 않는 상태  
    * 바닥의 물, 식어버린 부지깽이  
    
  **"엔트로피(무용한 에너지의 총량)는 극대점을 향해 움직이는 경향이 있다."**  
  
  
사람들은 적절한 기술만 개발하면 우리가 소모해버리는 것을 거의 모두 재생하여 재사용할 수 있을 것이라고 생각하지만 이것은 틀린 생각이다.  
오늘날 금속의 재생효율은 30% 정도이다. 재생을 위해서는 재생대상을 수거하고, 수송하고 가공하는데 별도의 에너지가 필요하기 때문에 결국 환경 전체의 엔트로피 총량이 늘어나게 된다.  
따라서 재생이라는 것은 유용한 에너지원을 희생하고 전체 환경의 엔트로피 총량을 증대시키는 대가를 치러야만 가능하다.  


지구가 우주에 대해 폐쇄계이고, 폐쇄계에서는 물질을 교환할 수 없기 때문 ->  
지구상의 물질적인 엔트로피는 끊임없이 증가하며 언젠가는 극대점에 도달할 것이다.  


매순간 산은 침식, 표토는 깎임 ->  
궁극적으로 재생가능한 자원도 재생불가능한 것이 됨  
결국 미래의 생명체에게 유용한 물질의 양이 줄어듦  

<br>
<br>

'집중도' : 에너지 수준과 엔트로피를 들여다보는 하나의 관점  

향수병 분자의 퍼짐 - 어떤 장소에 많은 양의 에너지가 있고, 인접한 장소에 매우 적은 에너지가 있을 때, 항상 많은 쪽에서 적은 쪽으로 평형이 이루어질 때까지 이동한다.  
이 현상은 "민주화를 향한 경향"  


* 맥스웰의 가설 - 외부 에너지를 사용하지 않고도 엔트로피 과정을 역행?  

    * 하나의 공간이 있다고 하자. 이 공간을 두 부분으로 나누고 고립된 상태로 '균일한 온도'의 기체가 들어있다. 분자를 다룰수 있는 물체를 가정하고 평균속도보다 빨리 움직이는 분자를 한 공간에 밀어넣고, 느리게 움직이는 분자를 다른 공간에 넣으면 한쪽은 뜨거워지고 한쪽은 차가워질 것이다. 그러면 온도차를 통해 열기관을 돌릴 수 있지 않을까?  
    
    * 분자의 속도와 방향을 감지하고 적절히 행동할 것이라고 생각했지만, 온도가 같은 양쪽 공간을 보려고 하면 균일한 방사량 때문에 열방사와 그 변화는 감지할 수 있지만 분자는 보지 못한다. 빛을 통해 방사평형이 깨져야 분자를 볼 수 있다는 결론이 나오는데, 그렇게 하여 분리하면 시스템 안에서 총 질서를 늘릴 수 있다고 하더라도 광원에서 더 큰 무질서와 더 큰 엔트로피가 발생하지 않으면 빛을 발생할 수 없다.  
    

"세상에 공짜는 없다."
    

<br>
<br>

* 루트비히 볼츠만 - "분명히" 대신 "아마도"  
    
    * 어느 정도까지 제2법칙의 유효함을 인정  
    
    * 폐쇄계에서 엔트로피가 증가한다는 점은 시인했지만 절대적인 진리로 받아들이지 않음  
    
    * 제2법칙을 확률, 통계의 법칙으로 끌어내리려고 함  
    에너지가 차가운 상태에서 뜨거운 상태로 이동할 가능성은 희박하지만 불가능하지는 않다는 주장  
    
    
* 에딩턴 - 볼츠만의 확률이론이 현실세계에서 한번이라도 실현될 가능성이 있는가?  
    
    * "두 개의 분리된 공간, 첫 공간은 공기, 두 번째 공간은 진공상태. 두 공간의 벽을 열면 공기가 전체에 골고루 퍼진다. 골고루 퍼진 공기분자가 불규칙하게 운동하다가 정확히 똑같은 시각에 공간의 한쪽으로 몰려갈 수도 있음을 시인하지만, 원숭이 떼가 타자기 위에서 뛰어놀다가 대영박물관에 있는 모든 책을 "쓸 수도"있을 것이라는 결론을 내린다. 물론 그 확률은 공기분자가 일시에 한쪽으로 몰릴 확률보다 훨씬 높다.  
    
    
    
* 니콜라스 죠르제스크, 레겐 - 좀더 직접적으로 핵심에 다가감  

    * 통계적 열역학에 대한 그의 비판은 기계론적 패러다임과 이제 부상하는 엔트로피 패러다임 사이의 싸움에 초점을  맞춤  
    
    * 우리는 일반인들이 통계적 역학, 더 정확히 말해 통계적 열역학으로 알려진 새로운 과학을 통해 물리학자들이 주장하는 바를 그대로 믿도록 오도당하고 있다는 사실을 시인해야 할 것이다.  
    우리가 그런 '기적'을 아직 보지 못한 것은 우리가  충분한 수의 잿더미와 시체를 관찰하지 못했기 때문이다.  
    
    
<br>
<br> 

### <정리>  

엔트로피 법칙은 폐쇄계에서 모든 에너지는 질서있는 상태에서 무질서한 상태로 이동해간다고 가르친다.  

* 엔트로피가 최소인 상태(집중도가 가장 높고 유용한 에너지가 가장 많은 상태)가 가장 질서 있는 상태  
* 엔트로피가 최고인 상태(유용한 에너지가 모두 소진되고 확산된 상태)는 가장 무질서한 상태  

<br>


한 곳에서 엔트로피 증가를 역행시키려면 다른 곳에서 엔트로피를 증가시켜야 하기 떄문에 결국 주변환경의 전체 엔트로피는 늘어날 수 밖에 없다는 것은 매우 중요하다.  

<br>
<br>


## 우주론과 제2법칙  

"제2법칙은 어디까지 적용될 수 있을까?  

* 헬름홀츠 - 엔트로피 법칙에 입각한 표준 우주이론을 내놓음  

    * **"열 죽음(heat death)"** : 우주는 조금씩 쇠락하여 궁극적으로는 엔트로피 극대점 또는 열 죽음 상태에 이른다는 것. 영원한 휴식상태. 모든 유용한 에너지가 소진되고 따라서 어떤 활동도 일어날 수 없다.  
    
<br>
<br>
    
    

* 대폭발 이론 - 오늘날 우주의 기원과 발전에 대해 가장 널리 받아들여지는 이론  

    * 고밀도 에너지가 팽창함에 따라 속도가 느려지고 그 안에서 은하, 항성, 행성 등이 생겨남  
    
    
* 정상우주론 - "우주는 분명히 팽창하고 있지만 '외부에서'우주로 마이너스 엔트로피를 주입해서 열 죽음이나 엔트로피 극대점을 피할 수 있다"  

    * 실험을 통해 먼 옛날에서 퀘이사, 전파원의 수가 지금보다 많았다는 것이 밝혀져 정상우주론은 틀림이 밝혀짐  
    * 정상우주론으노는 배경방사를 설명할 길이 없지만, 우주의 배경방사를 발견하였음  
    
    
* 순환이론 - 우주는 팽창단계와 수축단계를 끝없이 반복한다.  

    * 지금 팽창하고 있는 우주가 엔트로피 극대점에 달하면 우주는 다시 수축하기 시작해서 점점 더 질서있는 상태가 될 것이고, 결국 전우주는 원자핵 정도의 크기로 압축되고 다시 한번 폭발해서 팽창  
    * 현재로서는 이것을 뒷받침하거나 반박할 만한 실험결과가 너무 적음  

<br>
    
**현재로서 분명히 말할 수 있는 것은 광막한 우주 안의 조그만 태양계와 그 안의 행성인 지구에 관한 한 엔트로피 법칙은 모든 자연법칙 중 최고의 자리를 유지하고 있다는 사실**  


<br>
<br>

## 시간, 형이상학, 엔트로피  

"시간은 아무도 기다려주지 않는다", "시간은 흘러간다", "시간을 되돌릴 수는 없다" : 중요한 것은 우리가 경험하는 시간이 비가역적이라는 사실이다.  


엔트로피 과정을 역행시킬 수 있다면 모든 것을 처음 상태로 돌려놓을 수 있을 것이다.  

지구상에서 어떤 사건이 일어날 때마다 에너지가 소비되고 엔트로피 총량은 늘어난다. 세계가 시간이 없다고 말하는 것은 유용한 에너지가 고갈되어 간다는 뜻이다. "엔트로피는 시간의 화살이다"  


* 고대 그리스 세계관, 중세 기독교의 세계관 :  
역사를 질서로부터 쇠락으로 가는 과정으로 파악, 시간의 화살이 날라가는 방향과 엔트로피 과정을 올바로 이해하고 있음  

* 뉴턴 역학에 기초한 오늘날의 패러다임 :  
엔트로피 법칙을 무시하여 시간이 독립된 과정이라는 환상을 낳음  

<br>

시간은 일을 할 수 있는 유용한 에너지가 남아 있을 때만 존재한다.  
소비된 시간의 양은 소비된 에너지의 양에 비례한다.  

우주의 유용한 에너지의 고갈 -> 사건 빈도 감소  
열 죽음이면 어떤 사건도 일어나지 않음  


**엔트로피는 우리에게 시간의 방향을 알려주기는 하지만 속도를 알려주지는 못한다.**  
엔트로피 과정은 끊임없이 속도를 바꾼다. 우리는 시간을 뒤로 돌리거나 엔트로피 과정을 역행시킬 수는 없다. 그러나 우리는 엔트로피 과정이 발생하는 속도를 우리의 자유의지에 따라 결정할 수 있다.  
(지구상의 유용한 에너지를 얼마나 빨리 혹은 얼마나 천천히 소비할 것인가를 결정)  

<br>
<br>

## 생명과 제2법칙  

* 해롤드 블럼 - <시간의 화살과 진화>  
    * "생명체의 성장에 따른 부분적인 소량의 엔트로피 감소는 우주에서의 보다 큰 엔트로피의 증가를 수반"  
    

생명체의 주요 관심사 : 생명체들은 주변환경에서 자유 에너지를 흡수하여 엔트로피 과정의 반대방향으로  움직여갈 수 있다.  



`정상상태` : 생명체가 주변의 에너지를 빨아들여 평형상태로부터 멀리 떨어져  있으려는 상태  

마이너스 엔트로피야말로 생명체의 양식이다. 모든 생명체는 평형(죽음)을 향해 나아간다.  
살아남기 위한  투쟁은 어떤 생명체가 유용한 에너지를 흡수하는 능력을 얼마나 갖추고 있는가에  따라 판가름난다.  


<br>
<br>

물질과 에너지의 흐름을 극대화하는 것은 어떤 생태계의 발전 초기, 유용한 에너지가 아직 남아돌때 흔히 보이는 현상  
에너지 흐름이 극대점을 유지하는 초기 단계는 "식민화 단계"라고 불리면, 뒤에 오는 극소 에너지 흐름 단계는 "절정 단계"라고 불린다.  

특히 고도의 산업사회에 사는 사람들은 인간과 사회 시스템 모두에서 에너지 흐름이 계속 증가하는 쪽으로 활동하고 있다. 오늘날 인류가 당면한 위기는 전환의 위기이다. 다음 시대로 가면 인간은 절정 단계로 옮겨가서 인간 및 사회 시스템에서 에너지의 흐름을 극소화하는 방향으로 활동할 것이다.  

그러나 우리는  제2법칙이 생명과 진화의 진정한 기반이라는 사실을 깨닫고 인정하기 전에는 오늘날의 식민화 단계에서 절정 단계로 옮겨가지 못할 것이다.  


<br>
<br>

## 신체 외적 도구와 에너지  

`신체 외적 도구` : 인간이 유용한 에너지(마이너스 엔트로피)를 포착하고 변환시키고 처리하는 데 쓰이는 모든 도구를 포함  

모든 신체 외적 활동은 문화의 큰 부분을 이룬다. 사회발전이라는 것도 결국은 인간의 생존을 확보할 수 있는 '질서의 섬'을 만들어내려는 노력  

에너지는 인간의 삶의 기반이자 문화의 기반이기도 하다.  

* 권력 - 에너지를 변환, 교환, 폐기하는 신체 외적 도구를 통제하는 사람이 장악  

계층의 분화, 착취, 특권, 빈곤 등은 모두 한 사회의 에너지 흐름이 어떻게 설정되어 있는가에 따라 결정된다.  
신체 외적 도구를 통제하는 사람들이 에너지 흐름을 통제  
이들은 사회라는 테두리에서 어떻게 일을 배분할 것인가 결정  

<br>

학자들은 하나같이 자연의 법칙, 사회계약, 생산수단에 대한 변증법, 권력의 본질 등에 대해 역설하고 있지만 에너지 흐름이나 엔트로피 법칙에 대해서는 거의 한마디 없다.  

이제 막 떠오르는 엔트로피 패러다임이 정치학과 경제학을 비롯한 모든 학문 분야에 영향을 미치기 시작하면 이것을 거북하게 느낄 정치학자와 경제학자들이 많을 것  
하지만, 엔트로피 패러다임이 들어선다고 모든 학문이 정치학이나 경제학처럼 타격을 입는 것은 아니다.  

<br>

인류학자들은 사람들이 환경을 구성하는 방법에 변화가 발생한 시점을 기준으로 역사의 주요시기들을 나누었다. 각 시기의 특성을 살펴보고 이들 모두를 관통하는 하나의 끈을 들여다보는 것은 중요한데, 이 끈이 바로 엔트로피 법칙이다.  
















    




    
    





    


