---
title: "엔트로피 - 제 3부 새로운 역사관의 틀"
author: "Jae Kwan Koo"
output:
  html_document:
    fig_height: 6
    fig_width: 10
    highlight: textmate
    toc: yes
    toc_depth: 4
    toc_float: yes
  word_document: default
  github_document:
    toc: yes
    toc_depth: 4
---  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```  

## 제 3부 새로운 역사관의 틀  

<속담>  

역사의 퍼즐을 이해하는 열쇠는 엔트로피 법칙과 앞서 말한 `두 개의 격언`이다.  
역사를 개인 수준으로 끌어내리면 모든 것이 분명해진다.  
우리가 현재 삶의 방식에 대해 매우 만족하고 행복해한다고 하면, 우리는 생활방식을 근본적으로 바꾸는 일 따위는 생각지도 않을 것이다. "좋은 것을 부수지 말라"는 속담 그대로이다.  

* "행복한 사람들은 역사를 만들지 않는다." - 행복한 인간은 역사를 만들어낼 수 없다.(프랑스 속담)  

* "필요는 발명의 어머니이다."(미국 속담)  

<br>

역사의 `여유` 또는 `잉여` 이론 : 사람들의 행동양식에 중요한 변화가 생기는 것은 이들이 풍요의 결과 잉여를 충분히 축적해서 생각하고 실험할 수 있는 여유가 생겼을 때라는 것  

ex) 수렵채취인들이 충분한 잉여를 축적하지 못했다면 그들은 농경사회로 결코 옮겨가지 못했을 것이다.  

<br>

합리적인 주장처럼 보이지만, 자세히 보면 아귀가 맞지 않다.  

도대체 무엇 때문에 이 사람들이 자신들의 삶을 송두리째 뽑아가면서 불확실하고, 위험하며, 한번도 해보지 않은 밭갈기를 시작할 것인가?  
모든 것이 잘될 때 사람들은 자신의 생활양식을 결코 바꾸지 않는다.  

**우리는 기계관의 사고를 가져 이런 식의 사고를 할 수 밖에 없다.  
"새로운 도구와 기술로 인해 사람은 더 물질적 잉여를 이루게 되었고, 이로 인해 더욱 시간이 남아 더 발달된 도구 와 기술을 개발했고, 이는 더 큰 잉여를 낳는식으로 발전했다. 세계라는 기계는 더 효율되고 개선되고 확장되어 우리의 삶은 이 과정에서 더 안전하고 안락해졌다."  **

<br>


오늘날 남아있는 수렵채취사회에 대한 연구는 "결핍, 위기, 실험"의 이론을 뒷받침한다.  
수렵채취인들은 필요에 의해 `농경`을 시작했다.  
사냥감과 식용식물의 줄어듦, 새로운 사냥터도 사라졌고, 활동영역을 넓힌다는 것도 불가능해져 생존위기에 직면한 이들은 실험을 할 수 밖에 없었다.  


**역사란 제 2법칙의 반영**  

* 축적된 엔트로피로 인해 사회가 에너지원 자체에 대한 질적 변화를 꾀하는 때가 `역사의 분수령`이라는 시점  
* 전환의 시기에 낡은 방식은 쓸모없게 되어 엔트로피 총량이 너무 커져 새로운 에너지원으로 이동이 일어나고 새로운 방식의 기술이 태어나며 새로운 사회, 경제, 정치체제가 형성된다.  


인간은 육체만으로 늘어난 작업을 감당할 시간이 없기 때문에 인간은 적절한 수준의 생존을 유지하기 위해 더욱 복잡한 기술을 개발해야만 했던 것  

효율성이 한 단계 높아질 때마다 에너지의 분산가 무질서의 증가만 가속화되어 각 엔트로피 분수령 사이의 시간도 짧아졌다.  

* 수렵채취인->농업 : 수백만 년  
* 농경->산업산회 : 수천 년  
* 산업사회->? : 수백 년?  

백만 년 전과 비교할 때 오늘날 산업사회에서는 우리는 당시보다 1인당 1000배의 에너지를 소비ㅣ해야 생활을 영위할 수 있다.  
근육의 힘으로써가 아닌 기계에 의해 수행된다는 이유 한 가지 때문에 현재 우리가 일을 적게한다는 환상에 사로잡힌다면 슬픈 일이다.  


역사를 보면 식민화 단계에서 절정 단계로의 전환을 성공적으로 하여 에너지 흐름의 속도를 줄여 전체 환경의 엔트로피 증가를 감소한 문명도 있었다.  
정상상태로 들어간 문명들은 세계를 폐쇄계로 파악했다.  

<br>

현대적 세계관은 다른 모습을 보인다.  
기계 패러다임 - '끊임없는 성장' 이미지와 직결되어 한계라는 것은 패배의 조짐  

우주개발론자들은 다른 행성을 식민화해서 거기서 에너지를 얻을 수 있을 거라고 주장  
- 6일간의 인구 증가분에 해당하는 사람들을 우주로 쏘아올리는데도 전인류의 1년간 GNP를 모두 투입해야 한다.  
- 지구와 비슷한 기후조건의 가능성이 있는 행성은 10광년 떨어짐, 간다고해도 생명 유지할지는 미지수  
- 다른 행성에서 광물을 캐서 오는 것은 발견했다고 하더라도 지구까지 가져오는 비용을 감당할 방법이 없음  

지구라는 폐쇄계에 내재하는 물리적 한계를 인정하는 것이 우리 스스로를 완전히 구할 수 있는 길  
이제까지 우리가 지구에 입한 상처가 치유될 수 있는 자연적 재생과정에 필요한 시간을 충분히 준다면, 모든 생명이 건강하게 살 수 있을 것  

<br>
<br>

## 최후의 에너지 분수령  

13세기와 16세기 사이에 서유럽은 엔트로피 분수령을 거침(나무->석탄)  
서유럽의 생활방식도 근본적인 변화를 겪었다.  
중세에 종말을 고함과 동시에 산업혁명의 첫 장을 연 것  

중동의 토양이 메마른 데 비해 서유럽의 토양은 습하고 무거워서 쟁기질하기가 힘들었다.  

신형 쟁기를 통해 대륙의 발전은 큰 영향을 받음  
워낙 무거워 여덟 마리의 소가 한 조가 되어 끌어야 했다.  
소를 많이 갖고 있지 못해 농가들은 서로 협조해야 했다.  
=>농업생활의 구조를 바꿈  

북유럽의 장원경제에는 공동경작이 주류를 이루게 됨  

<br>

이 후, 두 가지 기술의 개발  

1. 땅이 기름진 북유럽 일부에는 인구가 늘어 수확량을 늘려야 했는데, 전통적인 2포식 농업(1/2이 노는 땅) 대신 3포식 농업의 시작(1/3만 노는 땅)  
수확량이 늘고, 쟁기질 작업량이 줄어듦  
토지 사용량 증가로 인해 지력을 빨리 소진시킴->엔트로피 과정 가속  


2. 3포식 농업의 도입에 따라 소를 말로 대체  
말은 두 배 빨리 일을 했지만, 풀뿐만 아니라 곡식도 먹여야 함. 다행히 귀리 수확량이 늘어 충당가능  

<br>

하지만 말을 경작에 이용하기 위해 세 가지 기술적 개선이 필요  
1. `마구`와 `편자`가 고안  
2. `말 두마리를 앞뒤로 부리는 방법`이 완성  


<br>

14세기 중엽이 되자 유럽인들은 엔트로피 분수령에 도달  
12세기 유럽 일부에서는 풍차를 이용해 과거에는 불모지였던 땅을 경작지로 바꾸는 데 성공했지만, 산림파괴와 인구증가라는 대가를 치루었다.  

<br>

16세기와 16세기 초에 걸쳐 영국의 목재 위기는 너무나 심각해져서 벌목을 규제하는 왕립위원회가 설립될 지경.  
1630년대 목재가격은 15세기말의 2.5배가 되었다.  

**목재->석탄**  
* 단순히 에너지 기반의 변화에 그치지 않음.  
* 에너지 기반이 바뀌자 생활방식 전체가 뿌리째 변화될 필요가 생김(사는 방식, 이동방식, 복장, 행동양식, 정부의 통치방식)  


오늘날 우리는 나무를 석탄으로 대치한 것이 대단한 발전이며, 진보를 향한 힘의 승리라고 생각한다.  
그 당시 사람들에게는 석탄은 열등한 에너지원으로 천대받았다. 더럽고 많은 오염물질을 내뿜었다.  

역사 속에서 누군가가 뭔가 좀더 나은 방법을 발명하면 우리는 그것을 위대한 진보라고 생각하는데 익숙해져 있다.  
사실 '더 나은 방법'이란 에너지를 추출하기 어려운 환경에 적응하기 위해 개발된 '다른 방법'일 뿐이다. 그리고 각 단계가 진행될 때마다 개발되는 새로운 방법은 궁극적으로 앞선 단계보다 더 많은 일 또는 에너지를 요구한다.  

현대식 증기기관은 석탄채굴을 좀 더 쉽게 하기 위해 설게되고 사용  
(채굴이 계속됨에 따라 갱도는 더욱 깊어졌고 따라서 석탄을 끌어올리기도 힘들어졌고 통풍도 어려워짐)  

석탄채굴과 관련된 문제가 해결되자마자 석탄의 운송문제가 생겼고 증기기관차와 철도의 발명으로 이어졌다.  

증기펌프와 증기기관차는 도끼, 말, 손수레 등 나무시대의 도구들보다 훨씬 복잡했고 많은 에너지를 소비했다.  
역사 전체에 걸쳐 기술의 질적인 변화는 항상 더욱 복잡하고 많은 에너지를 소비하는 방향으로 나아갔다.  

새 환경이 만들어질 때마다 인간은 더 많은 일을 해야 했을 뿐만 아니라 새로운 작업방식은 옛날 방식보다 더 열등한 대체물로 인식되었다.  

1. 가공식품vs천연식품  
가공식품은 생산에 필요한 에너지의 양은 천연식품보다 훨씬 많다. 가공식품을 선택하는 사람은 거의 없을 것  

2. 의복  
가죽이 희귀해지자 양털로 대치했는데, 17세기 18세기가 되자 인구증가로 인해 농경지 수요가 늘어 양의 방목은 경제성이 없어졌다.  
목초지를 경작지로 바꿀 것을 요구했고, 양털을 대체할 재료가 필요해졌다.  
면인데 해외 식민지에서 값싸게 재배하여 본국으로 수입하여 의복으로 가공하면 되었다.  

오늘날 합성섬유로 된 옷에 크게 의존하고 있는데, 선택하라고 하면 많은 사람들은 순면이나 양모로 된 옷을 선호할 것이다.  

<br>
<br>

## 기술  

기술이 복잡해지고 그 영역이 확장됨에 따라 우리는 점점 기술을 자연과는 독립된 것으로 인식한다.  
마치 무에서 유를 창조하는 것처럼, 신비로운 과정을 통해 기존의 에너지원에 처음보다 더 많은 것을 얻어내는 것처럼 기술을 본다.  
**단지 기존의 유용한 에너지를 소비할 뿐이다. 기술의 규모가 복잡할수록 에너지 소비량도 많아진다.**  

우리는 또한 기술이 더 큰 질서를 창조한다는 믿음에 사로잡혀 있다.(현실은 정반대이다)  

세계가 혼돈 속으로 깊이 빠져들수록 우리는 문제의 근원을 들여다보기를 꺼린다.  
대신 기술로 몸을 단단히 감싸고 모든 비판을 방어하지만 기술이 우리 주변환경에 대해 어떤 일을 저지르고 있는지 인식하지 못하며, 우리 자신에 대해서 어떻게 하고 있는지는 더 더욱 모른다. 우리는 우리가 옷도 잘 입고 잘 보호되고 있다는 허구에 매달리고 있다. 우리 자신이 만든 세계의 무질서한 파편 때문에 더욱 노출되고 더욱 위험에 빠지고 있으면서도 말이다.  


<br>
<br>

## 외부비용  

`외부비용` : 제품, 공정, 계획 또는 서비스에 의해 파생된 이른바 2차 효과의 결과로 발생하는 예상치 못한 비용  

우리는 모두 외부비용과 점점 친숙해진다.  
ex) 원자력 발전소 내 사고로 저준위 방사능이 대기 중에 유출되면 "피해보상은 누가 할 것인가?"  

외부비용은 엔트로피 법칙의 결말을 피해 가려는 손쉬운 방패일 뿐이다.  
"모든 기술은 주변환경에 더 큰 무질서를 창조하는 대가로 일시적인 '질서의 섬'을 만들고 있을 뿐"  


특정한 기술에 의해 파생된 2차적 무질서를 다른 기술을 적용하여 일시적으로 해결할 수 있지만, "모든 새로운 기술은 앞선 기술이 그것을 필요로 했기 때문에 탄생했다." 이것이 바로 제2법칙이며, 피해갈 길은 없다. 기술을 더 많이 도입하면 할수록 왜 세상은 고장 투성이가 되는지 우리는 아직도 의아해하고 있다.  

'변환자'의 수가 빨리 늘어날수록 유용한 에너지는 더 빨리 소비되고 분산과 무질서도는 커진다. 해결책보다 문제가 더 빨리 늘어나는 것이다.  


<br>

산업혁명 이전의 문명에서 기술은 그것이 수행하는 기능에 한정되어 있었지만, 기계 패러다임 안에서는 기술이 사람들의 행동방식을 결정한다.  
예측이 불가능하고 통제가 불가능한 상태인 불확정성의 섬들을 모두 제거하지 않고는 사회는 제 기능을 발휘하지 못한다는 것이 기계 패러다임의 주장이다.  

**해결책처럼 보이는 것은 결국 문제를 가속화시키는 결과를 낳는다.**  
사건이 전개될 때마다 엔트로피는 늘어나고 유용한 에너지는 줄어들기 때문에 새로운 문제들은 과거의 문제보다 해결하기 힘들다.  
문명 전체에 기술을 전파하려고 하면 사회는 점점 와해되고 복잡해지며 문제는 커지며 엔트로피가 증가하고 따라서 무질서도 늘어난다.  
이 모든 과정은 지수함수적으로 진행된다.  

<br>
<br>
## 기술의 수확체감  

1976년 개최된 의회 경제위원회 공동청문회에서 일부 기술 전문가들은 수화체감현상이 널리 퍼질 것이며, 과거에 미국이 누렸던 눈부신 기술진보는 다시는 오지 않을 것이라고 했다.  
지난 10년간 연구개발에 수십억 달러를 투자했는데도 100%의 시장잠재력을 가진 기술은 두 가지밖에 나오지 않았다는 것(주름이 가지 않는 바지, 휴대용 계산기)  

기술은 독립적이고 자생적인 힘이 아니라 에너지의 변환자일 뿐이다.  
그러므로 기술에서의 돌파구는 에너지원의 질적 변화에 이어 나타난다. 특정한 에너지 환경에 적합하도록 에너지를 변환시켜야 하므로 여기에 맞는 특정한 형태의 기술이 개발되기 때문이다.  
ex) 땅 속에서 캐낸 석탄의 에너지를 변환시키기 위한 증기기관  

파생기술의 단위비용은 그 기술이 개선되어감에 따라 점점 싸지지만, 새로운 기술이 계속 늘어나고, 엔트로피 값은 극대점을 향해 나아가며, 에너지 흐름의 전과정에서 수확체감의 법칙이 적용되기 시작한다.  

엔트로피 값은 극대점을 향해 나아가며, 에너지 흐름의 전과정에서 수확체감의 법칙이 적용되기 시작한다.  
환경으로부터 에너지를 끌어내는 일은 더욱 비싸지고 복잡해진다. 과거의 에너지 흐름으로 인해 생겨난 무질서는 계속 축적되며 그 압력은 더욱 거세져 새로운 기술적 가능성에 대해 더욱 큰 제약을 가한다.  

궁극적으로 새로운 에너지 환경에 따라 창출된 기술은 한계까지 왔고 이제 엔트로피 분수령을 향해 나아가고 있다.  

<br>
<br>

## 제도의 발달  

역사가들은 문화 또는 문명의 발전단계가 일정한 지점에 이르면 보편화하는 과정이 시작된다는 것을 알고 있다.  
다양한 경제적 및 정치적 활동을 좀더 중앙집중식으로 통제하는 체제를 굳건히 하려는 공동의 노력이 시작된다는 뜻  

각 기관과 제도는 더 크고, 복잡하고 중앙집중화되려는 경향이 있는데, 권력을 분산하고 책임과 통제권을 더 많은 사람들에게 부여하는 것으로 위기가 해결되는 일은 거의 없다.  

* 정치 및 경제기구 : 기계와 마찬가지로 에너지 변환자  
		* 문화전체를 통과하는 에너지 흐름을 더욱 원활히 함  

새로운 에너지 환경의 도약 단계에서 사람들은 에너지 흐름의 상당부분을 박탈당하는데, 그 에너지는 새로운 에너지 변환자의 기반을 건설하는 데 쓰인다.  

새로운 에너지 환경의 제 2단계에서는 보다 많은 에너지가 사회 시스템으로 직접 흘러든다.  
이 단계는 이미 1차적 기술기반이 갖추어진 상태이기 때문에, 이때부터 기술은 증식되기 시작하고 엔트로피 과정의 영향이 표면에 드러난다. 에너지 흐름이 전체에 걸쳐 더 큰 2차적 무질서를 만들어내기 때문이다.  

<무질서>  
1. 에너지를 다양한 제품이나 서비스로 변환하는 과정에서 파생  
2. 개인과 집단 간 에너지 교환에서 발생  
3. 에너지 폐기물에 의함  


흐름의 모든 단계에서 에너지는 변환되고, 교환되고, 폐기된다.  
이 과정에서 에너지는 항상 더욱 분산된 형태로 변하고, 엔트로피가 증가한다.  

흐름 전체에 걸쳐 무질서가 증가함에 따라 흐름 자체의 진행이 방해받는데, 흐름이 최대로 유지되기 위해 더 빨리 증가하는 무질서를 끊임없이 청소해주어야 한다.  
정치 및 경제기구들은 그 기능과 영역이 확대되어 유지보수기능을 행하기 시작한다.  
위기가 한 번 지나갈 때마다 관료체제는 비대해지는데, 기구들이 터져버리면 더욱 새롭고 크고 중앙집중적인 기구가 나타나 질서를 바로잡는 식의 순환이 계속된다.  


동시에 가능하다면 국가는 고갈되어가는 에너지를 보충하기 위해 새롭고 유용한 에너지원을 찾는다는 목적으로 영토확장을 꾀한다.  
* 제국주의적, 식민주의적 팽창 : 더 많은 에너지원을 확보하려는 노력  
		* 새로운 땅을 정복하려면 더 많은 에너지를 써서 군대, 무기, 통치기구 등을 공급(국가의 기구는 더욱 비대해지고 중앙집중화)  


<br>

마지막으로 사회는 제3단계에 도달.  
사회의 총체적 제도는 너무 중앙집중화되고 확장되엉 전체 시스템이 더 이상 감당할 수 없을 정도로 엄청난 에너지를 소비  
기업과 정부가 하는 일은 점점 작아지는 대신 운영을 위한 에너지는 점점 더 많이 소요된다  

총체적 제도 : 시스템 전체를 통해 에너지 흐름을 원활히 하기 위해 존재하는 것이지만 결국에는 그나마 남아 있는 에너지원의 대부분을 삼켜버린다.  

대부분의 인간사회가 존재의 절정 단계로 옮어가지 않고 식민화 단계에 계속 머물기로 한다면 위의 결과는 당연하다.  


오직 절정 상태에서만 이런 복잡성과 중앙집중화의 과정을 늦출 수 있다.  
에너지 흐름의 총량을 줄임으로써 엔트로피 과정은 느려지고 무질서 과정도 느려져 사회체제를 통해 에너지를 변환하는 역할을 맡은 기구도 팽창속도를 아주 느리게 묶어둘 수 있을 것이다.  

<br>
<br>

## 전문화  

전문화는 증가하는 복잡성 및 집중화와 나란히 진행된다.  

1965년 11월 9일 약 3000만 명의 미국인들은 지나치게 전문화된 사회에서 하나의 전문기능이 잘못되면 어떤 이리 벌어질 수 있는가를 경험  

캐나다 온타리오 주의 발전소에 발전소에서 릴레이 하나가 끊어짐->미국 북동부 전지역에 전력공급 중단->수만 명의 사람들이 엘리베이터나 지하철에 갇힘. 대서양 해안지역 전체에 엄청난 교통혼잡 발생. 조명, 난방 꺼짐  


우리는 지나치게 전문화된 사회가 드러내는 취약성의 예를 일상생활에서 자주 겪는다.  
제철소 노동자들의 파업이 길어졌다->철이 없으면 자동차 회사들은 차를 만들 수 없다->플라스틱, 유리 등 납품하는 협력업체들도 조업을 단축한다->어떤 지역 근로자 6명 중 1명이 자동차 관련 산업에 직간접적으로 종사하고 있다면 그 지역경제는 위축된다->소비자들의 구매력은 떨어지고, 고객이 줄어 백화점은 캐셔를 해고할 수 밖에 없다  


생물학자들에 의하면 지나친 전문화는 종의 멸종에 가장 중요한 역할을 한다고 한다.  
어떤 종이 특정한 생태계 내에서 지나치게 전문화되면 환경변화에 적응하지 못한다.  
전환에 대비할 수 있는 융통성과 다양성을 갖추지 못하는 것  

인간사회도 마찬가지이다. 오늘날 우리는 지나치게 전문화되고 또 기존의 에너지 환경에 너무 익숙해져 근본적으로 다른 에너지 환경으로 옮겨가는 데 필요한 융통성을 대부분 잃어버렸다.  

<br>
<br>

## 세계관과 에너지 환경  

어떤 문화가 개발한 특정한 기술과 제도는 그 문화가 속했던 특정한 에너지 환경을 비춰주는 거울  
**여러 가지 에너지 환경은 각각에 맞는 변환자가 필요**하기 때문  

어떤 문화의 세계관을 살펴보면 그 사람들이 왜 그러한 삶의 방식을 택했는지 알 수 있다. 에너지 환경이 변화면 사람들의 일하는 방법도 변해야 한다.  
즉, 환경에서 에너지는 변환하는 방법을 바꿔야 한다.  
(그렇다고 한 가지 에너지 환경에서는 한 가지 세게관밖에 나오지 않는것은 아니다.)  

<br>

어쨌든 세계관이라는 것은 적어도 그것이 속해 있는 에너지 환경과 조화를 이루거나 일치하기는 하는 것  
에너지 환경은 인간이 어떤 신념체계를 선택할 것인가에 대해 광범위한 한계를 설정  

ex) 뉴턴의 기계론적 패러다임  
재생불가능한 에너지(석탄과 석유)는 끊임없이 작은 단위로 분해가능하고 아무리 작아도 각 부분은 전체의 특성을 지니고 있다.  
재생불가능한 에너지원은 그 양이 고정되어 있고, 쉽게 계량화된다. 정확한 측정도 가능하다.  
뉴턴 패러다임은 수학공식, 측정에 대한 강조, 위치와 거리에 대한 관심을 통해 재생불가능한 에너지원을 효과적으로 착취하는 데 안성맞춤인 패러다임  

<br>


재생불가능한 에너지원이 있으므로 `저장된 태양(전등)`을 마음대로 껐다 켰다 할 수 있다.  
자기 마음대로 세계질서를 재편할 수 있다는 확신을 갖게 되었다. 시간은 통제할 수 있고, 에너지는 창조될 수 있으며, 물질적 진보는 보장된 것이다.  
삶과 그 활동들을 바라보는 새로운 방법에 합리적 근거를 부여한 것이 뉴턴의 패러다임  

<br>



인간은 재생불가능한 에너지원을 떠나 다시 한번 재생가능한 에너지원으로 옮겨 가려는 시점에 있어 이 패러다임은 도전에 직면해 있고 곧 포기될 것  


