---
title: "엔트로피 - 제 4부 재생불가능한 에너지와 다가오는 엔트로피 분수령"
author: "Jae Kwan Koo"
output:
  html_document:
    fig_height: 6
    fig_width: 10
    highlight: textmate
    toc: yes
    toc_depth: 4
    toc_float: yes
  word_document: default
  github_document:
    toc: yes
    toc_depth: 4
---  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```  

# 제 4부 재생불가능한 에너지와 다가오는 엔트로피 분수령  

## 에너지 위기  

총발전량 통계를 보면, 1970년에 미국은 석유, 천연가스, 석탄, 원자력 발전소에서 1조 7000만 킬로와트의 전력을 생산했는데, 미국을 제외한 세계 4대 소비국가(소련, 일본, 서독, 영국)의 발전량을 합친 것보다 많다.  

세계의 에너지 수요는 2000년이 되면 인구의 폭발적 증가로 인해 현재의 4배가 될 것으로 예상된다.  
지수함수적 인구증가 때문에 지구의 에너지 기반에는 상상을 초월하는 압력이 가해진다.  

"현재 채굴이 가능한 원유를 모두 뽑아올려 미국인에게 나눠주면 1인당 500배럴이 돌아간다. 또, 원유를 정유하면 1배럴당 42갤런의 휘발유가 나온다. 그러므로 보통의 미국인이 1갤런에 10마일 정도 달리는 대형 승용차를 타고 1년에 1만 마일씩 달릴 경우, 12년 후면 그에게 배정된 전세계의 석유 매장량이 사라진다."  

<br>
<br>

## 합성연료  

원유 매장량이 점점 줄어드는 대신 채굴, 처리, 소비와 관련된 비용은 점점 올라간다.  
이 때문에 많은 사람들이 석유 이외에 다른 재생불가능한 에너지원을 찾는 데 매달리고 있다.  

합성연료를 살펴보자.  
모든 합성연료는 뭔가를 합성해서 얻은 것이 아니고 재생불가능한 에너지원에서 파생된 것일 뿐이다.  

현재 계획은 1990년까지 석탄을 원료로 한 합성연료 휘발유 100만 배럴을 생산하는 것으로 되어 있다.  
한 백악관 관리는 "이 사업은 연방정부가 제시한 사업 중 가장 정신나간 것 중 하나가 될 가능성이 있다."  

1. 현재의 석탄액화기술로 석탄 1톤을 캐서 고온으로 가열하여 압력을 가해봐야 고작 3~4배럴 정도의 액체연료만 나온다.(합성연료 제조공정 단계마다 대량의 물 필요)  
미국 석탄 매장량의 대부분은 서부에 있고 따라서 합성연료공장도 이곳에 세워질 예정이다. 하지만 서부는 이미 물부족을 겪고 있다.  

2. 합성연료를 처리하려면 이를 위한 산업기반시설이 기초부터 모두 건설되어야 한다.  
정부계획대로 하루 100만 배럴을 생산하려면 적어도 50만 배럴짜리 공장 20개는 세워야 하는데, 정부는 공장 하나에 드는 건설 비용을 20억 달러로 잡고 있지만, 랜드 연구소의 예측에 다르면 다른 분야의 에너지 가격상승을 감안하여 계산해볼 때 합성연료공장 건설에는 정부예측보다 100% 정도의 비용이 더 든다는 것  
따라서 총비용은 1000억 달러에 달하는데 이 비용은 인간을 달에 보내기 위해 10년간 계속된 아폴로 계획에 투자한 금액의 4배에 해당한다.  
방대한 규모의 송유관, 수백만 톤의 석탄을 실어나를 수송시스템 등 모두 감안하여 뉴욕타임즈는 3000억 달러로 예측했다.  

3. 이 거대한 20개 공장을 어디에 건설하느냐?  
주민들은 모두들 더 많은 연료를 원하고 있지만, 자기가 사는 곳에 공장이 들어서는 것을 싫어한다.  


<br>

합성연료를 쓰면 온실효과가 더욱 가속될 것이다. 보통연료보다 이산화탄소를 더 많이 만들어 내기 때문이다.  
같은 양의 열을 얻는 데 있어 합성연료는 석탄의 1.4배, 석유의 1.7배, 천연가스의 2.3배의 이산화탄소를 방출한다.  

<br>
<br>

## 핵분열 에너지  

원자력 발전은 비용뿐만 아니라 현재로서는 해결할 수 없는 `사회적 및 건강상의 문제`를 일으킨다.  

1. 발전에 필요한 우라늄을 채굴하는 광부들이 암이나 기타 질병에 노출될 뿐만 아니라 우라늄 광산 근처에 사는 주민들에게 심각한 건강상 문제 야기  
이미 1억 톤 정도의 우라늄 폐석(반감기 8만년)으로 인해 선천적 결함을 가지고 태어나는 경우가 늘었다.  

2. 원자로 자체도 안전하지 못함  
미국의 모든 원자로는 끊임없이 소량의 방사능을 주변환경으로 방출하고 있음  
물론 업계 사람들은 방사능이 법적 기준 이하라고 하지만, 강하건 약하건 모든 방사능은 잠재적으로 위험하다는 의학적 증거가 존재한다는 사실은 말하지 않는다.  

3. 방사능에는 적정량이라는 것이 없음  
모든 방사능은 항상 지나치게 많다. 방사능 입자 하나가 암이나 돌연변이를 일으킬 수도 있다.  
발병과정이 매우 느려 방사능 노출로부터 발병까지는 20년잉 걸릴 수도 있다->오늘날 원자력 발전소 건설은 미래의 역병을 풀어놓는 일  

4. 원자력 발전소 1기당 매년 400~500파운드의 플루토늄이 만들어진다.  
미국의 원자력 발전소 하나는 매년 40개의 핵탄두를 만들 수 있을 만큼의 플루토늄을 생산  
원자탄을 만들 수 있는 기술적인 지식은 미국 내 도서관 어디를 가든 쉽게 얻을 수 있다는 사실을 감안할 때 플루토늄 생산은 사람들에게 "당신들 마음대로 핵폭탄을 만드시오"라고 권고하는 것과 같다.  

5. 핵폐기물 처리라는 해결 불가능한 문제  
원자력 연구개발에 그렇게 많은 노력을 기울이고, 발전소 건설에 수십 수백억 달러를 투자한 지금도 과학계, 전력회사, 정부는 핵폐기물 제거방법을 모르고 있음  
아직 핵폐기물 발생량이 적은 오늘날도 폐기장에서의 누출과 사고소식이 끊임없이 들려오고, 25만 년간 이를 추적관리해야 함과 동시에 무장경비원을 24시간 배치해야 한다.  

<br>
<br>

## 핵융합  

20년 전 미국인들은 핵분열 에너지가 '무한하고, 깨끗하며, 계산할 수 없을 정도로 싼' 에너지 시대를 열어줄 것이라는 약속에 열광  
여러 사고들로 인해 치명타를 입었음에도 불구하고 새로운 원자력의 가능성에 열광  
**그것은 핵융합**  

<br>


`핵분열` : 원자핵을 쪼갠다.  
`핵융합` : 서로 다른 원자 2개의 핵을 결합시킨다.  

태양에서 계속 일어나는 반응이 핵융합  
1950년대 인간은 수소폭탄을 통해 핵융합 반응을 배웠다.  
사실 수소는 바닷물에서 무한대로 얻을 수 있는데, 핵융합 발전이 현대의 영구기관에 해당한다고 볼 수 있지만, 엔트로피 법칙은 핵융합 발전 가능성에 심한 제약을 가하고 있다.  

1. 폐쇄된 공간 안에서 핵융합이 지속적으로 진행될 수 있다고 보장할 수 없다.  
사업적으로 수익성이 있으려면 핵융합로는 노심 1세제곱cm당 1초에 100조 개의 수소 원자를 융합시켜야 하지만, 현재까지 폐쇄된 공간에서의 핵융합 반응은 몇 분의 1초밖에 지속되지 못했다.  

2. 몇 가지 핵융합 기술이 나와 있지만, 주로 연구되고 있는 것은 중수소-3중수소 반응이라고 불린다. 삼중수소는 리튬으로 만드는데 리튬은 우라늄 만큼이나 희귀한 재생불가능한 자원이다. 따라서 핵융합 에너지원은 무한한 것이 아니다.  

3. 핵융합 발전이 '깨끗하다'고 하지만 이 깨끗함은 좀 기이하다.  
리튬 광산의 광부들은 우라늄 광산의 광부와 마찬가지로 건강상의 영향을 받을 것이다.  

구조물의 일부, 예를 들어 노심에 가장 가까운 벽 같은 것들은 매년 교체해야 할 것  
그러나 방사능이 워낙 강해 엄청난 비용을 들여 유지보수용 로봇을 따로 설계제작해야 한다.  

<br>

아모리 로빈스(물리학자이자 태양 에너지 예찬론자) - **"이 모든 기술적 및 자원상의 문제뿐만 아니라 핵융합 발전은 우리가 원하지 않는 요소들을 담고 있다. 즉, 핵융합 발전은 복잡하고, 돈이 많이 들고, 공사기간이 길며 중앙집중적이고 기술집약적인 발전방식이다."**  

<br>
<br>

## 광물  

환경에서 에너지를 추출하기 위해서는 시추기, 트랙터, 발전소 등 재생불가능한 자원을 사용해야 한다.  
에너지를 이용하여 일을 하려 해도 기계나 공장 등 재생불가능한 자원을 투입해서 만든 시설을 통해서만 가능  

많은 전문가들은 현재의 소비수준이 계속 유지된다면 적어도 75년후 세계 각국은 유용한 광물 가채 매장량의 반을 고갈시켜버릴 것이라고 주장  

<br>

**"2050년이 되면 미국 내 주석, 상업용 석면, 콜롬비움, 형석, 운모판, 고품질의 인, 스트론튬, 수은, 크롬, 니켈 등의 가채 매장량이 고갈될 것이다. 그나마 남아 있는 자원에 대한 각국의 경쟁이 치열해진 가운데 대부분의 주요 광물을 수입에 의존하면 가격은 올라갈 것이고 광물수출국들은 이것을 무기로 삼을 것이다.  
이는 OPEC 회원국들이 석유를 무기로 삼은 것과 같다."**  

고엔트로피 경제체제는 재생불가능한 자원을 너무 빨리 소비해버리기 떄문에 사실상 이들을 재생불가능한 자원으로 만들어버린다.  

어떤 사람들은 해저에서 캐내는 망간 덩어리가 비금속 광물수요를 충족시켜줄 수 있을 것이라고 하지만, 현 추세대로 증가한다면 100년 후, 바다에서 얼마쯤 건져올린다고 해야 몇 년혹은 몇 십 년을 버틸 수 있을 뿐, 그 이후에는 모든 광물이 완전 고갈될 것  

<br>
<br>

## 대체와 재생, 그리고 보전  

희귀한 광물을 덜 희귀한 광물로 대체하거나 기존의 광물으르 좀더 효과적으로 재생하면 재생불가능한 광물자원의 재고를 무한히 유지할 수 있을 것이라고 믿는 사람들이 여전히 존재한다.  

* 윌리엄 오퓔스  
    * "대체재는 일반적으로 당초 재료보다 효율이 떨어지고 따라서 주어진 기능을 수행하는 데 더 많은 에너지가 든다."  
    

<br>

재생은 광물자원의 고갈에 대한 해결책으로 자주 제시되지만, 재생도 열역학 제2법칙에서 예외가 될 수는 없음을 잊지 말아야 할 것  

어떤 광물이든 재생될 때마다 그 일부는 불가피하게 손실되어 회수가 불가능  
(오늘날의 재생효율은 대부분 금속의 경우 30%정도)  

<br>

`재생`과 마찬가지로 `보전`도 매우 중요하다.  
그러나 이것도 재생과 마찬가지로 부분적인 해결책일 뿐이다.  

보전은 절대적으로 필요한 일이지만 어떤 보전계획도 한계가 있음을 기억해야 한다.  
왜냐하면 이 계획은 기존의 고에너지 소비체제에 맞추어 시행되어야 하기 때문이다.  
현재의 소비체제에 조금이라도 제약을 가하는 보전계획은 에너지 흐름 여기저기에 심각한 왜곡 현상을 발생기킬 뿐이다.  

ex) **미국 정부의 에어컨 자동온도조절장치의 높은 온도 설정**  
전력소비를 줄이고자 노력했으나 에너지 흐름을 높은 수준으로 유지하도록 되어 있는 시스템을 그대로 둔 채 보전만 하려고 하면 어떤 문제가 생기는가를 보여준다.  

뉴욕의 세계 무역센터에서 캘리포니아의 홀리데이 인 호텔에 이르까지 미국 전지역에 세워진 건물들은 창문이 열리지 않도록 설계되었다. 당시 사람들은 완전히 폐쇄된 환경에서 1년 내내 쾌적한 냉난방을 공급할 수 있는 전력이 공급될 것이라고 생각했다. 그러나 자동온도조절장치의 온도를 높게 설정하면 건물 안에 있는 사람들은 가끔 창문을 열고 신선한 공기를 끌어들여야 한다. 그러나 이렇게 할 수 있는 방법은 수십만 개의 건물에 달려 있는 수백만 개의 창문을 바꾸는 것뿐이다. 이렇게 하려면 엄청난 에너지, 자원, 시간, 인력이 든다.  

<br>

이런 예를 들었다고 해서 최대한 보전을 해야 할 절대적 필요를 부정하려는 것은 아니다. 보전은 그 시스템이 허용하는 범위 내에서만 에너지의 흐름을 약간 낮출 수 있음을 지적하려는 것뿐이다.  

그러나 산업화되고 도시화된 사회는  에너지의 흐름을 극대화하는 방향으로 설계되어 고에너지 소비구조 하에서 보전을 통해 우리가 할 수 있는 일은 하찮을 수밖에 없다.  
